# 指定node，版本最新
FROM node:latest

# 创建文件夹
RUN mkdir -p /home/nodeNestjs

# 将根目录下的文件都copy到container
COPY ./ /home/nodeNestjs


# cd到 /home/nodeNestjs
WORKDIR /home/nodeNestjs

# 安装项目依赖包
RUN npm i -g npm
RUN npm i -g pnpm
RUN pnpm install
RUN npm run build

# 配置环境变量
ENV HOST 0.0.0.0
ENV PORT 3000

# 容器对外暴露的端口号
EXPOSE 3000

# 容器启动时执行的命令
CMD ["node", "/home/nodeNestjs/dist/main.js"]